# Generated by Django 3.0.8 on 2021-01-30 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('metric_type', models.CharField(choices=[('Reps', 'Reps'), ('Distance', 'Distance'), ('Calories', 'Calories')], max_length=20)),
                ('metric', models.CharField(choices=[('Weight', 'Weight'), ('Time', 'Time')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('AMRAP', 'AMRAP'), ('For Time', 'For Time')], max_length=20)),
                ('rounds', models.PositiveIntegerField(default=1)),
                ('time', models.TimeField(blank=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Workout')),
            ],
        ),
        migrations.CreateModel(
            name='MovementInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type_value', models.PositiveIntegerField(blank=True)),
                ('metric_value', models.PositiveIntegerField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.MovementClass')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.Section')),
            ],
        ),
    ]
