# Generated by Django 3.0.8 on 2021-01-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.DurationField(blank=True),
        ),
    ]
