# Generated by Django 3.0.8 on 2021-01-30 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210130_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
