# Generated by Django 3.0.8 on 2021-01-31 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20210130_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementinstance',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='workout.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='workout.Workout'),
        ),
    ]
