# Generated by Django 3.0.8 on 2021-01-31 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20210131_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementclass',
            name='name',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
