# Generated by Django 3.0.8 on 2021-01-31 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0005_auto_20210131_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementinstance',
            name='date',
        ),
    ]
