# Generated by Django 3.0.8 on 2021-02-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20210201_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
