# Generated by Django 3.0.8 on 2021-02-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20210204_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='scheduled_for',
            field=models.DateField(blank=True, null=True),
        ),
    ]
