# Generated by Django 3.0.8 on 2021-02-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_auto_20210205_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_type',
            field=models.CharField(choices=[('Strength', 'Strength'), ('MetCon', 'MetCon'), ('Conditioning', 'Conditioning')], default='Strength', max_length=20),
        ),
    ]
