# Generated by Django 3.0.8 on 2021-02-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_section_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementclass',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
