# Generated by Django 3.0.8 on 2021-02-10 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0013_auto_20210207_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementinstance',
            name='metric_type_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='movementinstance',
            name='metric_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
